name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: karkiparbat
          outputs: dist/snake.svg

      - name: Push snake to main branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: dist
          clean: true
          single-commit: true
